# Generated by Django 3.0.2 on 2021-01-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_roll_number', models.CharField(max_length=200)),
                ('phy_marks', models.IntegerField()),
                ('chem_marks', models.IntegerField()),
                ('math_marks', models.IntegerField()),
                ('total_marks', models.FloatField()),
                ('percentage', models.FloatField()),
            ],
        ),
    ]
